# Generated by Django 5.0.3 on 2024-04-06 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_remove_userprofile_is_staff_profilefeeditem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilefeeditem',
            old_name='created_pn',
            new_name='created_on',
        ),
    ]
